### PR TITLE
Bring back the term "content-agnostic"

### PR DESCRIPTION
**Pull request by brainwo**
"Content-agnostic" refers to the design of Anki being a content-free flashcard application allowing user to choose whatever deck they please and allowing them to create their own deck. Contrast to other flashcard applications like Wanikani where users of the application learn the same set of cards without any options to use the application for another purpose besides what it originally offered for.

The previous change to "highly customizable" lost this meaning.

Discussion: https://github.com/open-spaced-repetition/awesome-fsrs/commit/1d7bace84c449efb65bb34821e019bfe04515186#r146399797

### CODE REVIEW

**Comment by brainwo** [comment]
Some other suggestions also include "content-neutral" and "content-independent". But I would prefer to the term introduced in https://apps.ankiweb.net/.

**Comment by brainwo** [comment]
A glossary might be helpful.

**Comment by brainwo** [comment]
> Can we not write around that to avoid a noun string? To be more descriptive than that, can just tell people, simply, what Anki allows. Custom fonts, colours, emojis, photos, videos, audio, math symbols, etcetra, etcetra.

I think that's another discussion unrelated to this pull request

**Review by L-M-Sherlock — APPROVED** [review]
LGTM

**Pull request merged**
